### ISSUE TITLE
Startup Corner Vertrag unterschreiben

### ISSUE THREAD

**Issue by mahaupt** [mahaupt/menero-helm-charts#1]
... und die angefragten Dokumente abschicken

- [x] Marcel
- [x] Dom
- [x] Arvid
- [x] FH Logo auf Webseite einbauen?

**Comment by alpha-papa** [comment]
FH Logo einbauen mit so was wie "unterstützt von" oder "unsere partner" kp... ist auf jeden fall ne gute sache.

**Comment by mahaupt** [comment]
Wir bereiten nun den Vertrag für unsere Zusammenarbeit vor. Dazu benötigen wir folgende Dokumente (in Kopie) von allen Teammitgliedern:
- Foto im Passbildformat (für Zutrittskarten falls ein Büro benötigt wird)
- Gültiger Lichtbildausweis
- Meldezettel
- Aktuelle Inskriptionsbestätigung FH Campus Wien von mindestens einer/einem Gründer/in aus dem Team (Arvid Preuß)
